package com.margin.enums;

public enum LoadingStage {
    SCHEDULING,
    SCRAPING,
    PARSING,
    SOURCE_VERSIONING,
    NLP,
    NLP_GENDER_DETECTOR,
    NLP_THIRD_PARTY,
    NLP_LANGUAGE_TOOLS,
    NLP_TRANSLITERATION,
    STARTING_DATABASE,
    CONVERSION_TO_NODE,
    PERSISTING_NODE,
    COMPLETING_DATABASE,
    UNKNOWN
}
